### ISSUE TITLE
Please document <path:foo> syntax

### ISSUE THREAD

**Issue by TobiX** [tamland/kodi-plugin-routing#1]
I just switched my addon from xbmcswift2 to kodi-plugin-routing. Since the route syntax is slightly different between those 2, I promptly introduced a bug (cccc/plugin.video.media-ccc-de#5).

```
@plugin.route('/dir/<subdir>')
```

in xbmcswift2 matched "/dir/foo" and "/dir/foo/bar", while in kodi-plugin-routing it only matches the first. I realized that in kodi-plugin-routing, I can achieve the same be using the route

```
@plugin.route('/dir/<path:subdir>')
```

to restore the old behaviour. Since this is mentioned nowhere in the README, please add some kind of description of this feature, so other don't fall into the same trap as I did.

**Comment by da3dsoul** [comment]
Thanks for this. I wasn't looking for it, but it'll help.
