### ISSUE TITLE
Creating sub menu for Kodi addon?

### ISSUE THREAD

**Issue by leopheard** [tamland/kodi-plugin-routing#11]
Hi there,

Can I use this script to create a submenu for an addon? For example if I have:

```
@plugin.route('/')
def main_menu():
    """
    main menu 
    """
    items = [
    {
            'label': plugin.get_string(30010),
            'path': plugin.url_for('Music),
            'thumbnail': "test.jpg"},
    ]
    return items
```

How would I make a submenu when you click 'Music' that lists 'Rock', 'Pop', etc?

**Comment by tamland** [comment]
You need to use the regular `xbmcplugin` api. This module does routing only.
