### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by GianniDPC** [tamland/kodi-plugin-routing#28]
I have the following code in my main.py 
```
import routing
plugin = routing.Plugin()
```
On the second line if throws the following error: 

`2019-11-10 12:05:07.804 T:11008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Plugin'
                                            Traceback (most recent call last):
                                              File "C:\Users\Gianni\AppData\Roaming\Kodi\addons\plugin.video.yelo\routing.py", line 2, in <module>
                                                import routing
                                              File "C:\Users\Gianni\AppData\Roaming\Kodi\addons\plugin.video.yelo\routing.py", line 14, in <module>
                                                plugin = routing.Plugin()
                                            AttributeError: 'module' object has no attribute 'Plugin'
                                            -->End of Python script error report<--`

I am using version 0.2.3

**Comment by dagwieers** [comment]
I have a distinct feeling that you have another python module installed that is named "routing".

**Comment by GianniDPC** [comment]
Damn that was indeed the issue I renamed my main.py to routing.py in my plugin. I feel so stupid right now :(
