### ISSUE TITLE
Broken in v18 with reusepython

### ISSUE THREAD

**Issue by zach-morris** [tamland/kodi-plugin-routing#5]
[My addon](https://github.com/zach-morris/plugin.program.iagl) uses script.module.routing and I've found it's stopped working with the Kodi v18 alpha 2 nightlies.

I've narrowed it down to this change in Kodi:
https://github.com/xbmc/xbmc/pull/13814

The current issue is the routes are not followed with this change included in Kodi when using script.module.routing.  I can't quite figure out what the specific issue is, but I'm guessing it's the way sys.argv is called within the script.

**Comment by Rechi** [comment]
As mention in the kodi PR
> In order to work as expected, you have to refresh them (passing from default.py to submodules).

Here are the required changes
````
--- a/addon.py
+++ b/addon.py
@@ -5,6 +5,7 @@ from kodi_six import xbmc, xbmcaddon, xbmcplugin, xbmcgui, xbmcvfs
 xbmc.log(msg='IAGL:  Lets Play!', level=xbmc.LOGNOTICE)
 xbmc.log(msg='IAGL:  Version %(addon_version)s' % {'addon_version': xbmcaddon.Addon().getAddonInfo('version')}, level=xbmc.LOGDEBUG)
 import routing
+import sys
 from resources.lib.main import *

 try:
@@ -373,4 +374,4 @@ def iagl_text_viewer():
        IAGL_Dialog.doModal()

 if __name__ == '__main__':
-       plugin.run()
+       plugin.run(sys.argv)
````

**Comment by zach-morris** [comment]
Hmm, this doesnt seem to fully solve the issue.  The routes now work, but after selecting a listitem, then returning to the list to browse again, any subsequent selection does not work.
I can confirm that subsequent selections work normally if I add
```
<reuselanguageinvoker>false</reuselanguageinvoker>
```
to the addon.xml, so something still isn't working within the routing addon.  Nothing in the logs points to any issue - I'll keep digging into it to try and identify where the issue is.

**Comment by dagwieers** [comment]
Can you provide me with a minimal reproducer? Because I cannot reproduce this issue.

**Comment by zach-morris** [comment]
Kodi has since removed reuselanguageinvoker default change, so I think this issue is fixed on the Kodi side by default
